/**
 * Completing a table order, and the table coming back afterwards.
 *
 * The POS had no way to settle a table session at all -- there was no client
 * wrapper for POST /api/table-session/:id/payment, so "Complete" was never
 * wired to anything. The consequences chained:
 *
 *   session never reaches PAID/CLOSED
 *     -> the table never enters its cooldown
 *       -> it never returns to "available"
 *         -> the session stays ACTIVE, so the next customer scanning the same
 *            QR is handed the previous customer's order.
 *
 * And even once called, choosing UPI or Card recorded the payment as FAILED,
 * because only CASH and QR_CODE counted as settled on selection.
 */

const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");

const {
  isPaidOnSelection,
  COUNTER_SETTLED_METHODS,
} = require("../controllers/tableSessionController");

const { DEFAULT_COOLDOWN_MINUTES, buildCooldownUpdate } = require("../services/tableCooldownService");

// ---- which methods settle at the counter ----------------------------

test("REGRESSION: UPI settles as paid on selection", () => {
  assert.equal(isPaidOnSelection({ method: "UPI" }), true);
});

test("REGRESSION: Card settles as paid on selection", () => {
  assert.equal(isPaidOnSelection({ method: "CARD" }), true);
});

test("Cash still settles, as it always did", () => {
  assert.equal(isPaidOnSelection({ method: "CASH" }), true);
  assert.equal(isPaidOnSelection({ method: "QR_CODE" }), true);
});

test("methods that settle elsewhere do NOT auto-pay", () => {
  // Nothing has moved when the operator merely picks these.
  assert.equal(isPaidOnSelection({ method: "ONLINE" }), false);
  assert.equal(isPaidOnSelection({ method: "PAYMENT_LINK" }), false);
});

test("...but they do pay once the gateway confirms", () => {
  assert.equal(isPaidOnSelection({ method: "ONLINE", paymentStatus: "success" }), true);
  assert.equal(isPaidOnSelection({ method: "PAYMENT_LINK", paymentStatus: "success" }), true);
});

test("the method is matched case-insensitively", () => {
  assert.equal(isPaidOnSelection({ method: "upi" }), true);
  assert.equal(isPaidOnSelection({ method: "Cash" }), true);
});

test("a missing or unknown method never counts as paid", () => {
  for (const bad of [undefined, null, "", "BITCOIN", 42]) {
    assert.equal(isPaidOnSelection({ method: bad }), false, String(bad));
  }
  assert.equal(isPaidOnSelection(), false);
});

test("the counter list does not quietly include an online rail", () => {
  for (const rail of ["ONLINE", "PAYMENT_LINK", "WALLET", "SPLIT"]) {
    assert.ok(!COUNTER_SETTLED_METHODS.includes(rail), `${rail} must not settle on selection`);
  }
});

// ---- the table comes back on its own --------------------------------

test("REGRESSION: a settled table goes straight back into service", async () => {
  // It used to rest in `cleaning` for a configurable wait. That wait is gone:
  // the next party can be seated the moment the bill is settled.
  const update = await buildCooldownUpdate(null);
  assert.equal(update.status, "available");
  assert.equal(update.availableAt, null, "no deadline, because there is no wait");
  assert.equal(update.currentOrderId, null, "the finished order must be unlinked");
  assert.equal(update.currentOccupancy, 0, "and the guests cleared");
});

test("there is no wait left to configure", () => {
  assert.equal(DEFAULT_COOLDOWN_MINUTES, 0);
});

// ---- the QR serves a fresh order to the next customer ----------------

test("REGRESSION: a CLOSED session is not active, so the next scan starts fresh", () => {
  // findActiveSessionByTable decides what a scan is shown (the QR controller
  // uses the session controller's). If PAID or CLOSED appeared in this list,
  // the next diner would be handed the last one's bill.
  const ctrl = fs.readFileSync(path.join(__dirname, "..", "controllers", "tableSessionController.js"), "utf8");
  const fn = ctrl.slice(ctrl.indexOf("const findActiveSessionByTable"));
  const statuses = fn.slice(fn.indexOf("$in"), fn.indexOf("]", fn.indexOf("$in")));

  assert.ok(statuses.includes("OPEN"), "an open session is still the diner's own");
  assert.ok(!statuses.includes("CLOSED"), "a closed session must never be served to a new scan");
  assert.ok(!statuses.includes('"PAID"'), "nor a paid one");
});

test("the QR token itself is never regenerated by settling", () => {
  // The card printed and stuck to the table must keep working.
  const src = fs.readFileSync(
    path.join(__dirname, "..", "controllers", "tableSessionController.js"),
    "utf8",
  );
  assert.ok(!/qrToken\s*=/.test(src), "settling must not rewrite a table's QR token");
});

test("REGRESSION: a split settle writes its several ledger entries in order, inside the transaction", () => {
  // Mongoose refuses create() of several documents with a session unless
  // ordered: true, so every split (Cash + UPI) settle returned "Internal
  // server error". The unit tests mock the model, so this pins the call.
  const src = require("node:fs").readFileSync(require("node:path").join(__dirname, "..", "controllers", "tableSessionController.js"), "utf8");
  assert.match(src, /PaymentTransaction\.create\(\s*parts\.map\([\s\S]*?\{ session: mongoSession, ordered: true \}\s*\);/);
});

// ---- money taken off a table needs the Security PIN ------------------

test("REGRESSION: voiding a dish, closing unpaid and discounting a table all ask staff for the PIN", () => {
  // Cancelling a whole order was PIN-guarded, so voiding it one dish at a
  // time got around the rule; /close freed an unpaid table for any token.
  const route = fs.readFileSync(path.join(__dirname, "..", "routes", "tableSessionRoute.js"), "utf8");
  assert.match(route, /\/items\/:itemId\/cancel"\)\.post\(isVerifiedUser, requireProtectedAction, cancelSessionItem\)/);
  assert.match(route, /"\/:id\/close"\)\.post\(isVerifiedUser, requireProtectedAction, closeSessionWithoutPayment\)/);
  assert.match(route, /"\/:id\/discount"\)\.post\(isVerifiedUser, requireProtectedAction, setDiscount\)/);
  assert.match(route, /const \{ requireProtectedAction \} = require\("\.\.\/middlewares\/requirePermission"\)/);
});

// ---- Release Table never frees an unpaid bill -------------------------

test("REGRESSION: Release Table refuses while a dish is still on the session", async () => {
  // The order read Served (the old auto-complete timer), so the live-order
  // check passed and the table was freed with its bill unpaid.
  const Module = require("module");
  const orig = Module._load;
  const tableUpdates = [];
  const session = { status: "OCCUPIED", items: [{ status: "preparing" }], timeline: [], async save() {} };
  Module._load = function (r) {
    if (r === "../models/tableModel") {
      return {
        findOne: async () => ({ _id: "t1", restaurantId: "r1", status: "occupied" }),
        findOneAndUpdate: async (f, u) => { tableUpdates.push(u); return u; },
      };
    }
    if (r === "../models/tableSessionModel") return { findOne: async () => session };
    if (r === "../models/orderModel") return { find: () => ({ select: async () => [{ _id: "o1", orderStatus: "Served", items: [] }] }) };
    return orig.apply(this, arguments);
  };
  delete require.cache[require.resolve("../controllers/tableController")];
  let failure = null;
  try {
    const { releaseTable } = require("../controllers/tableController");
    await releaseTable(
      { params: { id: "507f1f77bcf86cd799439011" }, user: { restaurantId: "r1", _id: "u1" } },
      { status() { return this; }, json() {} },
      (err) => { failure = err; },
    );
  } finally {
    Module._load = orig;
    delete require.cache[require.resolve("../controllers/tableController")];
  }
  assert.equal(failure?.status, 409);
  assert.equal(session.status, "OCCUPIED");
  assert.deepEqual(tableUpdates, []);
});
