/**
 * Completing a table order, and the table coming back afterwards.
 *
 * The POS had no way to settle a table session at all -- there was no client
 * wrapper for POST /api/table-session/:id/payment, so "Complete" was never
 * wired to anything. The consequences chained:
 *
 *   session never reaches PAID/CLOSED
 *     -> the table never enters its cooldown
 *       -> it never returns to "available"
 *         -> the session stays ACTIVE, so the next customer scanning the same
 *            QR is handed the previous customer's order.
 *
 * And even once called, choosing UPI or Card recorded the payment as FAILED,
 * because only CASH and QR_CODE counted as settled on selection.
 */

const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");

const {
  isPaidOnSelection,
  COUNTER_SETTLED_METHODS,
} = require("../controllers/tableSessionController");

const { DEFAULT_COOLDOWN_MINUTES, buildCooldownUpdate } = require("../services/tableCooldownService");

// ---- which methods settle at the counter ----------------------------

test("REGRESSION: UPI settles as paid on selection", () => {
  assert.equal(isPaidOnSelection({ method: "UPI" }), true);
});

test("REGRESSION: Card settles as paid on selection", () => {
  assert.equal(isPaidOnSelection({ method: "CARD" }), true);
});

test("Cash still settles, as it always did", () => {
  assert.equal(isPaidOnSelection({ method: "CASH" }), true);
  assert.equal(isPaidOnSelection({ method: "QR_CODE" }), true);
});

test("methods that settle elsewhere do NOT auto-pay", () => {
  // Nothing has moved when the operator merely picks these.
  assert.equal(isPaidOnSelection({ method: "ONLINE" }), false);
  assert.equal(isPaidOnSelection({ method: "PAYMENT_LINK" }), false);
});

test("...but they do pay once the gateway confirms", () => {
  assert.equal(isPaidOnSelection({ method: "ONLINE", paymentStatus: "success" }), true);
  assert.equal(isPaidOnSelection({ method: "PAYMENT_LINK", paymentStatus: "success" }), true);
});

test("the method is matched case-insensitively", () => {
  assert.equal(isPaidOnSelection({ method: "upi" }), true);
  assert.equal(isPaidOnSelection({ method: "Cash" }), true);
});

test("a missing or unknown method never counts as paid", () => {
  for (const bad of [undefined, null, "", "BITCOIN", 42]) {
    assert.equal(isPaidOnSelection({ method: bad }), false, String(bad));
  }
  assert.equal(isPaidOnSelection(), false);
});

test("the counter list does not quietly include an online rail", () => {
  for (const rail of ["ONLINE", "PAYMENT_LINK", "WALLET", "SPLIT"]) {
    assert.ok(!COUNTER_SETTLED_METHODS.includes(rail), `${rail} must not settle on selection`);
  }
});

// ---- the table comes back on its own --------------------------------

test("a settled table goes into cooldown rather than straight back", async () => {
  // No DB connection here, so cooldownMinutesFor falls back to the default.
  const update = await buildCooldownUpdate(null);
  assert.equal(update.status, "cleaning");
  assert.ok(update.availableAt instanceof Date);
  assert.equal(update.currentOrderId, null, "the finished order must be unlinked");
  assert.equal(update.currentOccupancy, 0, "and the guests cleared");
});

test("the default wait is the 2 minutes that was asked for", () => {
  assert.equal(DEFAULT_COOLDOWN_MINUTES, 2);
});

test("the cooldown deadline is roughly the configured wait away", async () => {
  const before = Date.now();
  const update = await buildCooldownUpdate(null);
  const waitMs = update.availableAt.getTime() - before;
  const expected = DEFAULT_COOLDOWN_MINUTES * 60 * 1000;
  assert.ok(Math.abs(waitMs - expected) < 5000, `expected ~${expected}ms, got ${waitMs}ms`);
});

// ---- the QR serves a fresh order to the next customer ----------------

test("REGRESSION: a CLOSED session is not active, so the next scan starts fresh", () => {
  // getActiveSessionForTable decides what a scan is shown. If PAID or CLOSED
  // appeared in this list, the next diner would be handed the last one's bill.
  const qrRoute = fs.readFileSync(path.join(__dirname, "..", "routes", "qrRoute.js"), "utf8");
  const fn = qrRoute.slice(qrRoute.indexOf("getActiveSessionForTable"));
  const statuses = fn.slice(fn.indexOf("$in"), fn.indexOf("]", fn.indexOf("$in")));

  assert.ok(statuses.includes("OPEN"), "an open session is still the diner's own");
  assert.ok(!statuses.includes("CLOSED"), "a closed session must never be served to a new scan");
  assert.ok(!statuses.includes('"PAID"'), "nor a paid one");
});

test("the QR token itself is never regenerated by settling", () => {
  // The card printed and stuck to the table must keep working.
  const src = fs.readFileSync(
    path.join(__dirname, "..", "controllers", "tableSessionController.js"),
    "utf8",
  );
  assert.ok(!/qrToken\s*=/.test(src), "settling must not rewrite a table's QR token");
});
