#!/usr/bin/env bash
# =============================================================================
# Knot Kitchen — nightly backup script (cron-friendly)
# =============================================================================
# What this backs up:
#   1. deploy/.env                (the ONLY secret on the VPS)
#   2. knotkitchen_caddy_data     ACME account key + issued certificates
#   3. knotkitchen_backend_uploads  menu media (only meaningful when
#                                 MEDIA_STORAGE_PROVIDER=local — the default)
#   4. knotkitchen_csd_documents  restaurant KYC/GST/FSSAI + signed agreements
#   5. knotkitchen_onboard_data   the onboard portal's database.json
#                                 (agents + agreements) — this is a PRIMARY
#                                 datastore with no Atlas equivalent; if this
#                                 volume is lost, the data is simply gone
#   6. knotkitchen_onboard_uploads  KYC documents uploaded via the portal
#   7. MongoDB                    full mongodump of the Atlas cluster
#
# Volumes 4-6 and the MongoDB dump were missing from this script until
# 2026-08-30, which meant every restaurant compliance document, the whole
# onboarding datastore, and (on an Atlas free tier, which has no snapshots of
# its own) the entire database were outside the backup set. If you add a
# volume to docker-compose.yml that holds state, add it to VOLUMES below.
#
# What this does NOT back up:
#   * External object storage (S3/Cloudinary) — configured to keep versions
#                            at the provider side.
#   * knotkitchen_caddy_config — regenerated by Caddy on start.
#   * Container images     — rebuilt on every deploy from the source repo.
#
# OFFSITE: set KNOT_BACKUP_REMOTE to an rclone remote (e.g. "r2:knot-backups")
# and the encrypted archive is copied there after every run. Leave it unset and
# the backup stays on the same VPS it is backing up — which does not survive
# losing the host. The script says so loudly on every run.
#
# Recommended cron entry (as root):
#   17 3 * * *   /srv/knot/deploy/backup.sh >> /var/log/knot-backup.log 2>&1

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUT_DIR="${KNOT_BACKUP_DIR:-/var/backups/knotkitchen}"
mkdir -p "$OUT_DIR"

# ---------------------------------------------------------------------------
# Dead-man's switch.
#
# A cron job that stops running is silent. You discover it on the day you need
# the backup, which is the worst possible day. If KNOT_BACKUP_HEARTBEAT_URL is
# set (Healthchecks.io, Better Stack, Cronitor — anything that alerts when a
# expected ping does NOT arrive), this script pings:
#
#   <url>/start   when it begins
#   <url>         on success
#   <url>/fail    on ANY failure, via the EXIT trap
#
# The monitor alerts on a missing ping, so it catches the cases logging cannot:
# the VPS being down, cron being disabled, the disk being full before the
# script even starts.
#
# Pings NEVER affect the backup's own exit status — a monitoring outage must
# not turn a good backup into a failed one.
# ---------------------------------------------------------------------------
HEARTBEAT_URL="${KNOT_BACKUP_HEARTBEAT_URL:-}"

ping_heartbeat() {
  [[ -n "$HEARTBEAT_URL" ]] || return 0
  command -v curl >/dev/null 2>&1 || return 0
  curl -fsS -m 10 --retry 3 -o /dev/null "${HEARTBEAT_URL}${1:-}" 2>/dev/null || \
    echo "[$(date -Is)] WARNING: heartbeat ping '${1:-success}' failed (backup itself unaffected)"
}

TMP="$(mktemp -d)"

# Fires on every exit path. A non-zero status pings /fail so the monitor alerts
# immediately rather than waiting for the next missed window.
on_exit() {
  local rc=$?
  rm -rf "$TMP"
  if [[ "$rc" -ne 0 ]]; then
    echo "[$(date -Is)] backup FAILED (exit $rc)"
    ping_heartbeat "/fail"
  fi
  return "$rc"
}
trap on_exit EXIT

echo "[$(date -Is)] backup starting"
ping_heartbeat "/start"

if [[ -z "$HEARTBEAT_URL" ]]; then
  echo "[$(date -Is)] NOTE: KNOT_BACKUP_HEARTBEAT_URL unset — a cron job that"
  echo "[$(date -Is)] NOTE: silently stops running will not be noticed."
fi

# 1. env file
cp "$REPO_ROOT/deploy/.env" "$TMP/env"

# 2-6. Every Docker volume that holds state. A volume that does not exist yet
# is skipped with a warning rather than failing the run — a fresh VPS may not
# have started the onboard portal yet — but a volume that exists and fails to
# archive IS fatal, because a silently partial backup is worse than none.
VOLUMES=(
  knotkitchen_caddy_data
  knotkitchen_backend_uploads
  knotkitchen_csd_documents
  knotkitchen_onboard_data
  knotkitchen_onboard_uploads
)

for vol in "${VOLUMES[@]}"; do
  if ! docker volume inspect "$vol" >/dev/null 2>&1; then
    echo "[$(date -Is)] WARNING: volume $vol does not exist — skipping"
    continue
  fi
  echo "[$(date -Is)] archiving $vol"
  docker run --rm \
    -v "$vol":/data:ro \
    -v "$TMP":/backup \
    alpine tar -C /data -czf "/backup/${vol}.tar.gz" .
done

# ---------------------------------------------------------------------------
# 7. MongoDB dump.
#
# On an Atlas M0 (free) cluster there is NO backup of any kind — snapshots
# start on paid tiers and point-in-time restore is M10+. Until the cluster is
# upgraded, this dump is the ONLY copy of orders, menus, stores, users and
# payments that exists anywhere. It is therefore fatal by default if it cannot
# run: a nightly archive that silently contains every KYC document but no
# database is the exact trap this script is meant to close.
#
# Set KNOT_BACKUP_SKIP_MONGO=true to opt out deliberately — do that only once
# the cluster itself has snapshot backups you have verified.
#
# The URI holds a password, so it is read straight out of deploy/.env into a
# variable and never echoed, never passed on a visible command line beyond the
# mongodump invocation itself.
# ---------------------------------------------------------------------------
if [[ "${KNOT_BACKUP_SKIP_MONGO:-false}" == "true" ]]; then
  echo "[$(date -Is)] WARNING: KNOT_BACKUP_SKIP_MONGO=true — database NOT backed up."
else
  if ! command -v mongodump >/dev/null 2>&1; then
    echo "mongodump is not installed, so the database would NOT be in this backup." >&2
    echo "Install the MongoDB Database Tools:" >&2
    echo "  https://www.mongodb.com/docs/database-tools/installation/" >&2
    echo "  (Ubuntu: apt-get install -y mongodb-database-tools)" >&2
    echo "Or set KNOT_BACKUP_SKIP_MONGO=true if the cluster has its own snapshots." >&2
    exit 1
  fi

  MONGODB_URI="$(sed -n 's/^MONGODB_URI=//p' "$REPO_ROOT/deploy/.env" | head -1)"
  # Tolerate MONGODB_URI="..." / MONGODB_URI='...' in the env file.
  MONGODB_URI="${MONGODB_URI%\"}"; MONGODB_URI="${MONGODB_URI#\"}"
  MONGODB_URI="${MONGODB_URI%\'}"; MONGODB_URI="${MONGODB_URI#\'}"

  if [[ -z "$MONGODB_URI" ]]; then
    echo "MONGODB_URI not found in deploy/.env — cannot back up the database." >&2
    exit 1
  fi

  echo "[$(date -Is)] dumping MongoDB"
  # --archive + --gzip produce one file. Errors are surfaced but the URI is
  # scrubbed from anything mongodump prints, since it embeds the password.
  if ! mongodump --uri="$MONGODB_URI" --archive="$TMP/mongodump.archive.gz" --gzip \
       2> >(sed -E 's#mongodb(\+srv)?://[^ ]*#mongodb://<redacted>#g' >&2); then
    echo "mongodump FAILED — refusing to write a backup without the database." >&2
    exit 1
  fi
  echo "[$(date -Is)] mongodump OK ($(du -h "$TMP/mongodump.archive.gz" | cut -f1))"
fi

# Bundle into one encrypted archive so it's safe to ship anywhere. Passphrase
# is provided via KNOT_BACKUP_PASSPHRASE — MUST be set in the crontab.
if [[ -z "${KNOT_BACKUP_PASSPHRASE:-}" ]]; then
  echo "KNOT_BACKUP_PASSPHRASE not set — refusing to write an unencrypted backup."
  exit 1
fi

OUT_FILE="$OUT_DIR/knot-$STAMP.tar.gz.gpg"
tar -C "$TMP" -czf - . | gpg --batch --yes --passphrase "$KNOT_BACKUP_PASSPHRASE" \
    --symmetric --cipher-algo AES256 -o "$OUT_FILE"

echo "[$(date -Is)] wrote $OUT_FILE ($(du -h "$OUT_FILE" | cut -f1))"

# ---------------------------------------------------------------------------
# Offsite copy.
#
# The archive is already encrypted with AES256 above, so the destination does
# not need to be trusted — only durable. Failure here is FATAL: a backup that
# only ever existed on the machine it is protecting has not really been taken,
# and cron must mail someone about it rather than logging a green line.
# ---------------------------------------------------------------------------
if [[ -n "${KNOT_BACKUP_REMOTE:-}" ]]; then
  if ! command -v rclone >/dev/null 2>&1; then
    echo "KNOT_BACKUP_REMOTE is set but rclone is not installed. Install it" >&2
    echo "(https://rclone.org/install/) and configure the remote, or unset" >&2
    echo "KNOT_BACKUP_REMOTE to accept a local-only backup." >&2
    exit 1
  fi
  echo "[$(date -Is)] copying to $KNOT_BACKUP_REMOTE"
  rclone copy --no-traverse "$OUT_FILE" "$KNOT_BACKUP_REMOTE"
  echo "[$(date -Is)] offsite copy OK"
else
  echo "[$(date -Is)] WARNING: KNOT_BACKUP_REMOTE is not set — this backup"
  echo "[$(date -Is)] WARNING: lives only on this VPS and will be lost with it."
fi

# Rotate LOCAL copies: keep the last 14 nights. Remote retention is the
# destination's job (bucket lifecycle rule) — this script never deletes there.
find "$OUT_DIR" -type f -name 'knot-*.tar.gz.gpg' -mtime +14 -delete

# Local breadcrumb, so `stat` on this file answers "when did a backup last
# actually succeed?" without parsing logs or trusting the monitor.
date -Is > "$OUT_DIR/.last-success"

echo "[$(date -Is)] backup complete"
ping_heartbeat
